### ISSUE TITLE
Unable to Authenticate with Bunq

### ISSUE THREAD

**Issue by swavans** [bunq/sdk_csharp#114]
## Steps to reproduce:
1.             var apiContext = ApiContext.Create(ApiEnvironmentType.SANDBOX, "YOURAPIKEY", "TestNotebook");

## What should happen:
1. Authenticate/Connect to Bunq

## What happens:
1.Bunq.Sdk.Exception.BadRequestException: 'Response id to help bunq debug: 886cb1c0-4d65-4732-a637-abe86f68e2db. 
 Error message: User credentials are incorrect. Incorrect API key or IP address.'

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [1.0.0-beta]
- [X ] Sandbox
- [ ] Production

**Comment by OGKevin** [comment]
Are you sure you are using a sandbox generated API key 😊 ?

I have a feeling this is not a bug in the SDK but rather you not correctly consuming the API 🤔

**Comment by swavans** [comment]
Yep my bad
