### ISSUE TITLE
MonetaryAccountSavings missing from endpoints

### ISSUE THREAD

**Issue by Want100Cookies** [bunq/sdk_csharp#118]
## Steps to reproduce:
Use `MonetaryAccount.List()` to retrieve all monetary accounts.

## What should happen:
Get a LIST of all Monetary Accounts including the MonetaryAccountSavings.

## What happens:
The SDK only provides with Bank, Joint and Light accounts and not Savings.

## SDK version and environment
- Tested on [1.1.0](https://github.com/bunq/sdk_csharp/releases/tag/1.1.0)
- [x] Sandbox
- [x] Production

**Comment by robinvanpoppel** [comment]
While the savings accounts code seem to be available in `1.10.3.0`, I am having trouble retrieving them. I am getting the following exception when calling `MonetaryAccount.List`.
```
Newtonsoft.Json.JsonSerializationException: 'Error setting value to 'SavingsGoalProgress' on 'Bunq.Sdk.Model.Generated.Endpoint.MonetaryAccountSavings'.'

InnerException:
InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Double]'.
```

**Comment by th0mk** [comment]
I'm getting the same error. Monetary accounts are available, they're just bugged right now.

**Comment by th0mk** [comment]
Interesting note: The endpoints were regenerated 2 days ago in commit [70986b7](https://github.com/bunq/sdk_csharp/commit/70986b7cf434cf2dcba9d14a82f0194a756f5b68) but it still seems to be bugged.
