### ISSUE TITLE
JsonSerializationException when logging in (ApiContext.Create)

### ISSUE THREAD

**Issue by InhouseMedia** [bunq/sdk_csharp#135]
## Steps to reproduce:
1.
Log in with ApiContext.Create()

## What should happen:
1.
Make use of api
## What happens:
1.
JsonSerializationException

Newtonsoft.Json.JsonSerializationException: "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Bunq.Sdk.Model.Generated.Object.LabelUser' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\nPath '[2].UserCompany.director_alias', line 95, position 25."

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_csharp/releases/tag/0.12.4)
- [ ] Sandbox
- [X] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by tbotting** [comment]
Having the same for the Java SDK. It's been almost 24 hours now.

**Comment by InhouseMedia** [comment]
Have made a pull-request that solves the issue
https://github.com/bunq/sdk_csharp/pull/136

**Comment by loedeman** [comment]
The same issue here (production), would be very nice if the PR got published asap ;)...

**Comment by tbotting** [comment]
Sorry for being harsh, but I believe as a bank, completely breaking your SDKs overnight and taking this much time to fix it is not acceptable.

**Comment by mason-chase** [comment]
I cannot believe Bunq make a change to API model without updating Document or SDK Nuget ,
This is a breaking change, when is the nuget going to be updated?

**Comment by lexym** [comment]
Hey, guys 👋We've resolved the issue. It must work now.

**Comment by mason-chase** [comment]
Are we back to original? Can you please clarify? I patched SDK manually to accept Array of DirectoAlias Object and today it stopped working again today!
