### ISSUE TITLE
DirectorAlias model has changed in production from a single object to array of objects

### ISSUE THREAD

**Issue by mason-chase** [bunq/sdk_csharp#137]
## Steps to reproduce:
1. there is a breaking change in Bunq response,
Authorization via API barcode on a company account can't map it,
the json response has array of objects 

## What should happen:
1. Should return a Object of BunqUser

## What happens:
1. Serialization error:
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Bunq.Sdk.Model.Generated.Object.LabelUser' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '[2].UserCompany.director_alias', line 306, position 25.
```

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_csharp/releases/tag/0.12.4)
- [ ] Sandbox
- [ X ] Production

**Comment by InhouseMedia** [comment]
same as:
https://github.com/bunq/sdk_csharp/issues/135
there's a fix but needs to be merged

**Comment by mason-chase** [comment]
I cannot believe Bunq make a change to API model without updating Document or SDK Nuget ,
This is a breaking change, when is the nuget going to be updated?

**Comment by lexym** [comment]
Fixed :) https://github.com/bunq/sdk_csharp/issues/135

**Comment by mason-chase** [comment]
Are you putting Object back into response? 
We were just presenting today to client and our app went into exception error.

@Bunq Can you please decide what is your final response is going to look like? Is it going to break again?
