### ISSUE TITLE
Monetary account joint cannot be retrieved.

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_csharp#50]
## Steps to reproduce:
1. Create a new joint account
2. try something like MonetaryAccount.list

## What should happen:
1. Monetary account joints are also listed

## What happens:
1. you will get all accounts except the new joint accounts

## Logs
- Logs `no logs` 

## Extra info:
- Tested on [0.12.3](https://github.com/bunq/sdk_csharp/releases/tag/0.12.3)

## Reference
- bunq/sdk_php#76

**Comment by gldrenthe89** [comment]
Any ETA on this?

**Comment by OGKevin** [comment]
@gldrenthe89 This is not really SDK related but rather API. The API does not provide this information. I suggest you create a topic on https://together.bunq.com requesting this 👍 . Once its available in the public API, it can and will be implemented in the SDK.

**Comment by gldrenthe89** [comment]
Thanks

Met vriendelijke groet,

Geert Lucas Drenthe

On 5 Jan 2018, 21:18 +0100, Kevin Hellemun <notifications@github.com>, wrote:

@gldrenthe89<https://github.com/gldrenthe89> This is not really SDK related but rather API. The API does not provide this information. I suggest you create a topic on https://together.bunq.com requesting this 👍 . Once its available in the public API, it can and will be implemented in the SDK.

**Comment by OGKevin** [comment]
Fixed in #113
