### ISSUE TITLE
Provided client public key has an incorrect modulus length. Modulus length must be "2048", got "1024"

### ISSUE THREAD

**Issue by M0rph3v5** [bunq/sdk_csharp#92]
## Steps to reproduce:
1. Create an Azure Function which runs the following code:

> BunqContext.LoadApiContext(ApiContext.Create(ApiEnvironmentType.SANDBOX, "key", "description"));

## What should happen:
1. Assume no error and a succesfull session start

## What happens:
1. Errors! -> Provided client public key has an incorrect modulus length. Modulus length must be "2048", got "1024"

## SDK version and environment
- Tested on latest code with the netstandard support
- [x] Sandbox
- [ ] Production

## Response id
- Response id: 21d9ad87-f23b-406e-a5e7-5c7e92167fd6 

## Extra info:
runs on netstandard,

**Comment by OGKevin** [comment]
Thanks for reporting @M0rph3v5 

As you've provided a response id I take it that this error came in back from the API and that no exception was thrown in the SDK itself as an actually SDK error ? 

@michielpost do you mind looking into this one ?

**Comment by M0rph3v5** [comment]
@OGKevin that's correct, searching provides me with:

https://github.com/bunq/sdk_csharp/issues/26#issuecomment-361884281

Having that same issue, but on .net 4.6 referring to https://github.com/dotnet/corefx/issues/12388 

Not sure if that's related at all though, the SecurityUtils seems to handle the RSA key size the correct way.

**Comment by OGKevin** [comment]
@M0rph3v5 no need for full response, thats what the response id is for :P. 

Ill take a look at this and see whats up. C# is not one of my strongest skills however so any help is appreciated.

**Comment by M0rph3v5** [comment]
@OGKevin hah makes sense :P, it isn't my strong suit either. I just want to build stuff with it, not run in these vague problems 😅

**Comment by OGKevin** [comment]
@BasvdM thanks for this! 

Do you mind creating a pull request ?

**Comment by OGKevin** [comment]
@BasvdM i think this explains it well enough: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

Also make sure when you make a commit the following is in the commit msg: `bunq/sdk_csharp#92`.

Let me know if you manage if not ill do it my self 😉

**Comment by sanderlanghorstredhotminute** [comment]
Running sdk_csharp 1.0.0 with a .net 4.7 application generates the same errors, still. When is this being fixed?
