### ISSUE TITLE
.net standard 2.0 support

### ISSUE THREAD

**Issue by fschaal** [bunq/sdk_csharp#93]
Realy great to see the new SDK! Any chance we will see added support for .net standard 2.0 soon?

**Comment by OGKevin** [comment]
Hey @fschaal,

See #26 

It is indeed on the roadmap, however feel free to contribute this your self! As my c# skills are not as good as the other 3 SDK's. Zo i would have to do some reaserch on this topic to even know what needs to be done to make the SDK work on higher .net standards.

**Comment by fschaal** [comment]
@OGKevin, sure I will see if I can add support for .net standard 2.0 :) I'll let you know if I have any questions.

**Comment by OGKevin** [comment]
@fschaal appreciate  it.

**Comment by OGKevin** [comment]
@fschaal that is good to hear, let me know if changes are required in the generated code. Once you have the port done and created a merge request ill take a look at the tests.
